-- MySQL Script generated by MySQL Workbench
-- Thu Dec  2 14:39:05 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hospital
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hospital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospital` DEFAULT CHARACTER SET utf8 ;
USE `hospital` ;

-- -----------------------------------------------------
-- Table `hospital`.`tb_productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`tb_productos` ;

CREATE TABLE IF NOT EXISTS `hospital`.`tb_productos` (
  `codProductos` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(200) NOT NULL,
  `unidad_medida` VARCHAR(10) NOT NULL DEFAULT 'U',
  `Stock` INT NOT NULL,
  `Precio Unitario` DECIMAL(3,2) NOT NULL,
  PRIMARY KEY (`codProductos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`tb_vale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`tb_vale` ;

CREATE TABLE IF NOT EXISTS `hospital`.`tb_vale` (
  `codVale` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `producto` INT NOT NULL,
  PRIMARY KEY (`codVale`),
  CONSTRAINT `fk_Vale_Producto1`
    FOREIGN KEY (`producto`)
    REFERENCES `hospital`.`tb_productos` (`codProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `hospital`.`tb_solicitud_compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`tb_solicitud_compra` ;

CREATE TABLE IF NOT EXISTS `hospital`.`tb_solicitud_compra` (
  `codSolicitud_Compra` INT NOT NULL AUTO_INCREMENT,
  `codCatalogo` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `unidad_medida` VARCHAR(10) NOT NULL DEFAULT 'U',
  `precioUnitario` DECIMAL(6,2) NOT NULL,
  `Descripcion` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`codSolicitud_Compra`, `codCatalogo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`tb_solicitud_bodega`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`tb_solicitud_bodega` ;

CREATE TABLE IF NOT EXISTS `hospital`.`tb_solicitud_bodega` (
  `codBodega` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `producto` INT NOT NULL,
  PRIMARY KEY (`codBodega`),
  CONSTRAINT `fk_Solicitud_Bodega_Producto1`
    FOREIGN KEY (`producto`)
    REFERENCES `hospital`.`tb_productos` (`codProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `hospital`.`tb_solicitud_almacen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`tb_solicitud_almacen` ;

CREATE TABLE IF NOT EXISTS `hospital`.`tb_solicitud_almacen` (
  `codsolicitud_almacen` INT NOT NULL,
  `Cantidad_Solicitada` INT NOT NULL,
  `Cantidad Despachada` INT NOT NULL,
  `producto` INT NOT NULL,
  PRIMARY KEY (`codsolicitud_almacen`),
  CONSTRAINT `fk_Solicitud_Almacen_Producto1`
    FOREIGN KEY (`producto`)
    REFERENCES `hospital`.`tb_productos` (`codProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `hospital`.`tb_solicitud_fondo_circulante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`tb_solicitud_fondo_circulante` ;

CREATE TABLE IF NOT EXISTS `hospital`.`tb_solicitud_fondo_circulante` (
  `codfondo_circulante` INT NOT NULL AUTO_INCREMENT,
  `Cantidad_Solicitada` INT NOT NULL,
  `Costo_Estimado` INT NOT NULL,
  `almacen` INT NOT NULL,
  PRIMARY KEY (`codfondo_circulante`),
  CONSTRAINT `fk_tb_solicitud_fondo_circulante_tb_solicitud_almacen1`
    FOREIGN KEY (`almacen`)
    REFERENCES `hospital`.`tb_solicitud_almacen` (`codsolicitud_almacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
